name: Testing and CI / CD

on:
  push:
    branches: main
    paths-ignore:
    - 'ansible/**'
    - 'terraform/**'
    - 'kubernetes/**'
    - 'monitoring/**'
    - '**.md'

jobs:

  Testing the Application:
    name: Testing the Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: pip install -r --no-cache-dir requirments.txt

    - name: Test with pytest
      run: python3 -m pytest

  Building Dcoker Image:
    name: Updating Docker Image
    runs-on: ubuntu-latest

    needs: Testing the Application

    env:
      REPOSITORY: grad_project # Define Dockerhub repo here
      IMAGE_TAG: v0.0.1 # Define the image tag here

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .

    - name: Push Docker image
      run: docker push "${{ secrets.DOCKER_USERNAME }}"/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
